apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt  # Mounted automatically inside the pod
    server: https://kubernetes.default.svc   # ✅ Use in-cluster API
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: jenkins-sa
  name: jenkins-context
current-context: jenkins-context
users:
- name: jenkins-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImhfV0Y1SnhTbFV0RFdLS3hVX1J5b1UyYmtRTWpNdXl2V3czdHJHSHg4MmcifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoyMDY5MjUwMzQxLCJpYXQiOjE3NTM4OTAzNDEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiY2FlMTk3NjEtMjM4Mi00M2U4LWFlMTMtZGQ4ZDU1Nzk4ZjQ2Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJqZW5raW5zLXNhIiwidWlkIjoiZjcyNDZhYjgtOWE4My00N2JiLWFkODgtMGU3ZDRlYzhhNGU4In19LCJuYmYiOjE3NTM4OTAzNDEsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpqZW5raW5zLXNhIn0.AoYzlYnzqUcHapNTIlfi_QldKXaG-kgBmztraUI076U7Kmx8B--OpAUW_SzxXCb6l8dE2bxrBernz79PL-65w4JDeii-Vf-tByE2R0gSaiJVqRWNFg1jVx_JT4IHXhISRLs_BfI-JVUqXGB6aLG9aIYNbrIarvCSfdQ1GTLcoHy3VsAlILX4EzU9ktOYcX8QgZQEI8_Bzdt-bYY5Fz3ti2QYyM1_cclWtoC3kJVJeelFOCvYdd0s6Q_bsJDPSr35mMU2MJc8yVGAtcLcdWz2j-Uox7Qx3JsHVteRzQ7aUFGtUUdMFjwOdU0M8wcKoJtBBZmPj9hDUsJgDfjMiSmy0g
